const data = {
    products: [
        {
            shirt: "Free Shirt",
            slug: "free-shirt",
            category: "shirts",
            image: "/images/shirt1.jpg",
            price: 0,
            brand: "Nicke",
            rating: 4.5,
            numReviews: 13,
            countInStock: 6,
            description: "Just a simple free shirt",
        },
        {
            shirt: "Fit Shirt",
            slug: "fit-shirt",
            category: "shirts",
            image: "/images/shirt2.jpg",
            price: 70,
            brand: "Abibas",
            rating: 4.8,
            numReviews: 16,
            countInStock: 8,
            description: "Just a simple shirt",
        },
        {
            shirt: "Slim Shirt",
            slug: "slim-shirt",
            category: "shirts",
            image: "/images/shirt3.jpg",
            price: 70,
            brand: "Raiymond",
            rating: 4.1,
            numReviews: 223,
            countInStock: 67,
            description: "Simple a slim shirt",
        },
        {
            shirt: "Fit Pants",
            slug: "fit-pants",
            category: "pants",
            image: "/images/pants1.jpg",
            price: 22,
            brand: "Abibas",
            rating: 3.2,
            numReviews: 77,
            countInStock: 33,
            description: "Simple fit pants",
        },
        {
            shirt: "Golf Pants",
            slug: "golf-pants",
            category: "pants",
            image: "/images/pants2.jpg",
            price: 28,
            brand: "Abibas",
            rating: 3.9,
            numReviews: 44,
            countInStock: 23,
            description: "Simple golf pants",
        },
        {
            shirt: "Slim Pants",
            slug: "slim-pants",
            category: "pants",
            image: "/images/pants3.jpg",
            price: 87,
            brand: "Lakkoste",
            rating: 4.7,
            numReviews: 45,
            countInStock: 21,
            description: "Simple slim pants",
        },
    ]
}
export default data